Repository pallets-eco/wtforms, pull requests merged in 2020-10, with the labels that each got.

#657 Re-enable coverage
  setup.cfg
  src/wtforms/i18n.py
  src/wtforms/validators.py
  tox.ini
Labels: tests

#660 Split field tests
  tests/fields/__init__.py
  tests/fields/test_boolean.py
  tests/fields/test_custom.py
  tests/fields/test_date.py
  tests/fields/test_datetime.py
  tests/fields/test_decimal.py
  tests/fields/test_defaults.py
  tests/fields/test_field.py
  tests/fields/test_file.py
  tests/fields/test_filters.py
  tests/fields/test_flags.py
  tests/fields/test_float.py
  tests/fields/test_form.py
  tests/fields/test_hidden.py
  tests/fields/test_html5.py
  tests/fields/test_integer.py
  tests/fields/test_label.py
  tests/fields/test_list.py
  tests/fields/test_month.py
  tests/fields/test_password.py
  tests/fields/test_radio.py
  tests/fields/test_select.py
  tests/fields/test_selectmultiple.py
  tests/fields/test_string.py
  tests/fields/test_submit.py
  tests/fields/test_textarea.py
  tests/fields/test_time.py
  tests/test_fields.py
Labels: refactoring, tests

#661 Fixed SelectMultipleField validation when using choices list shortcut
  CHANGES.rst
  src/wtforms/fields/core.py
  tests/fields/test_selectmultiple.py
Labels: bug

#671 Updated README to include Starlette integration
  README.rst
Labels: documentation
