Repository pallets-eco/wtforms, pull requests merged in 2023-10, with the labels that each got.

#768 Update documentation following _get_translations removal
  CHANGES.rst
  docs/i18n.rst
Labels: documentation

#797 implement a readonly and a disabled validator
  CHANGES.rst
  docs/validators.rst
  src/wtforms/validators.py
  src/wtforms/widgets/core.py
  tests/validators/test_disabled.py
  tests/validators/test_readonly.py
Labels: enhancement

#739 `SelectField` choice refactoring
  CHANGES.rst
  docs/fields.rst
  src/wtforms/fields/choices.py
  src/wtforms/widgets/core.py
  tests/conftest.py
  tests/fields/test_select.py
  tests/fields/test_selectmultiple.py
Labels: enhancement

#812 fix documentation examples
  docs/widgets.rst
  src/wtforms/fields/choices.py
  src/wtforms/widgets/core.py
Labels: documentation

#809 Select(Multiple)Field choice can be None if validate_choice is False
  CHANGES.rst
  src/wtforms/fields/choices.py
  tests/fields/test_select.py
  tests/fields/test_selectmultiple.py
Labels: bug

#813 unit tests improvements
  pyproject.toml
  tests/conftest.py
  tests/fields/test_form.py
  tests/fields/test_html5.py
  tests/fields/test_list.py
  tests/test_csrf.py
  tests/test_form.py
  tests/test_i18n.py
  tests/test_locale_babel.py
  tests/test_widgets.py
  tests/validators/test_regexp.py
Labels: tests
