Repository pallets-eco/wtforms, pull requests merged in 2023-07, with the labels that each got.

#789 Coerce function example
  docs/fields.rst
Labels: documentation

#795 fix style warnings
  src/wtforms/widgets/core.py
  tests/test_csrf.py
  tests/validators/test_anyof.py
  tests/validators/test_data_required.py
  tests/validators/test_input_required.py
  tests/validators/test_lazy_proxy.py
  tests/validators/test_length.py
  tests/validators/test_optional.py
Labels: tests

#796 docs: improve filters documentation
  src/wtforms/fields/core.py
Labels: documentation

#765 Implemented WeekField
  CHANGES.rst
  src/wtforms/fields/datetime.py
  tests/fields/test_week.py
Labels: enhancement
